package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
)

// List/Card 相關 resolver 已移至 list.resolvers.go, card.resolvers.go

// 型別轉換工具
func strToPtr(s string) *string { return &s }
func ptrToStr(s *string) string {
	if s == nil {
		return ""
	} else {
		return *s
	}
}

// 取得 userID string from context
func UserIDFromContext(ctx context.Context) (string, bool) {
	uid, ok := ctx.Value(struct{ UserID string }{}).(string)
	return uid, ok
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
