// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"trello-backend/internal/handlers"
	"trello-backend/internal/repository/postgres"
	"trello-backend/internal/services"
)

// Injectors from wire.go:

// InitializeAPI 初始化 API 相依性
func InitializeAPI(db *gorm.DB, jwtSecret string) (*handlers.AuthHandler, error) {
	userRepository := postgres.NewUserRepository(db)
	authService := services.NewAuthService(userRepository, jwtSecret)
	authHandler := handlers.NewAuthHandler(authService)
	return authHandler, nil
}

// wire.go:

var userRepositorySet = wire.NewSet(postgres.NewUserRepository)

var serviceSet = wire.NewSet(services.NewAuthService)

var handlerSet = wire.NewSet(handlers.NewAuthHandler)
