basePath: /
definitions:
  models.APIResponse:
    properties:
      error:
        example: 錯誤訊息
        type: string
    type: object
  models.ChangePasswordRequest:
    properties:
      new_password:
        example: newpass123
        type: string
      old_password:
        example: oldpass123
        type: string
    required:
    - new_password
    - old_password
    type: object
  models.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  models.LoginResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      name:
        example: 王小明
        type: string
      password:
        example: password123
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: Trello 後端 API 文件
  title: Trello 後端 API
  version: "1.0"
paths:
  /api/auth/change-password:
    post:
      consumes:
      - application/json
      description: 使用者變更密碼功能
      parameters:
      - description: 變更密碼資訊
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 密碼變更成功
          schema:
            $ref: '#/definitions/models.APIResponse'
        "400":
          description: 無效的請求資料
          schema:
            $ref: '#/definitions/models.APIResponse'
        "401":
          description: 認證失敗
          schema:
            $ref: '#/definitions/models.APIResponse'
      security:
      - BearerAuth: []
      summary: 變更使用者密碼
      tags:
      - 認證
  /login:
    post:
      consumes:
      - application/json
      description: 使用電子郵件和密碼登入並返回 JWT 令牌
      parameters:
      - description: 登入資訊
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登入成功
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: 無效的請求資料
          schema:
            $ref: '#/definitions/models.APIResponse'
        "401":
          description: 帳號或密碼錯誤
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: 使用者登入
      tags:
      - 認證
  /register:
    post:
      consumes:
      - application/json
      description: 註冊新使用者並返回 JWT 令牌
      parameters:
      - description: 註冊資訊
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 註冊成功
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: 無效的請求資料
          schema:
            $ref: '#/definitions/models.APIResponse'
        "500":
          description: 內部伺服器錯誤
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: 使用者註冊
      tags:
      - 認證
schemes:
- http
swagger: "2.0"
